event.InvocationEvent.getException()\n  method.\n